//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignPatternDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public int STT { get; set; }
        public string HoaDonID { get; set; }
        public string MaMH { get; set; }
        public int SoLuong { get; set; }
        public int DonGia { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual MATHANG MATHANG { get; set; }
    }
}
